add_rules("mode.debug", "mode.release")
add_requires("opengl", "sdl2", "glew", "glm", "assimp", "imgui")

target("robot_sim")
    set_kind("binary")
    add_files("src/*.cpp")
    add_files("src/*/*.cpp")
    add_headerfiles("include/*.h")
    add_includedirs("include")
    add_packages("opengl", "sdl2", "glew", "glm", "assimp", "imgui")