add_rules("mode.debug", "mode.release")
add_requires("opengl", "libsdl2", "glew", "glm", "assimp")

target("imgui")
	set_kind("static")
	add_files("extern/imgui/*.cpp")
	add_includedirs("extern/imgui/")

target("robot_sim")
    set_kind("binary")
    add_files("src/*.cpp")
    add_files("src/*/*.cpp")
    add_includedirs("include")
    add_includedirs("extern")
    add_packages("opengl", "libsdl2", "glew", "glm", "assimp")
    add_deps("imgui")
